openapi: 3.0.3
info:
  title: Wefit Challenge API - OpenAPI 3.0
  version: 1.0.0
servers:
  - url: http://localhost:4568/api
tags:
  - name: Person
paths:
  /person/create:
    post:
      tags:
        - Person
      summary: Create a person
      description: Create a person in database
      operationId: postPerson
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Person'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
            application/xml:
              schema:
                $ref: '#/components/schemas/Person'
        '400':
          description: Bad Request - Some fields is invalid
        '401':
          description: Invalid or undefined authorization header
        '409':
          description: Conflict - Person already exists
        '500':
          description: Internal Server Error
components:
  schemas:
    Person:
      type: object
      properties:
        personType:
          type: string
          example: '1'
          enum:
            - NATURAL_PERSON = 1
            - LEGAL_PERSON = 2
        cnpj:
          type: string
          example: '57.240.262/0001-40'
        cpf:
          type: string
          example: '825.186.670-75'
        name:
          type: string
          example: 'Zé'
        phone:
          type: string
          example: '(69) 2847-9557'
        cellPhone:
          type: string
          example: '11912341234'
        email:
          type: string
          example: kaue.tiago.rezende@nextel.com.br
        termsAccept:
          type: boolean
          example: true
        zipCode:
          type: string
          example: 76963-732
        street:
          type: string
          example: Avenida Cuiabá
        number:
          type: string
          example: 387
        complement:
          type: string
          example: ''
        city:
          type: string
          example: Cacoal
        neighborhood:
          type: string
          example: Centro
        state:
          type: string
          example: RO
